
spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/examplesdb?useUnicode=true&serverTimezone=Asia/Seoul
    url: jdbc:mysql://127.0.0.1:3306/examplesdb?useUnicode=true&serverTimezone=Asia/Seoul
    username: mysql
    password: mysql1234
    jpa:
      show_sql: true
      hibernate:
        ddl-auto: update
      properties:
        format_sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect
